name: remind_me
description: Flutter application.
version: 0.0.1+1

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.8.0
  obs_foundation:
    git:
      url: ssh://application-lifecycle.factory.orange-business.com:22/ads/DX2/practice-flutter/_git/obs_foundation
      ref: refs/tags/v1.2.2
  shared_preferences: ^2.0.20
  flutter_localization: ^0.1.10
  intl: ^0.17.0
  flutter_riverpod: ^2.0.2
  riverpod_annotation: ^2.0.2
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  riverpod_lint: ^1.2.0
  path_provider: ^2.0.14
  faker: ^2.1.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  test: ^1.21.0
  riverpod_generator: ^2.1.4
  custom_lint: ^0.3.2
  isar_generator: ^3.0.5

flutter:
  uses-material-design: true
  generate: true
